- swagger: "2.0"
  info:
    title: Pinboard User API
    version: ~
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /user/api_token/:
      get:
        summary: User Api Token
        description: Returns the users API token (for making API calls without a password)
        operationId: user-api-token
        responses:
          200:
            description: OK
        tags:
        - links
        security: []
    /user/secret:
      get:
        summary: User Secret
        description: Returns the users secret RSS key (for viewing private feeds)
        operationId: user-secret
        responses:
          200:
            description: OK
        tags:
        - links
        security: []
  definitions: []