- swagger: "2.0"
  info:
    title: API for Importation Applications
    description: API for Exhibit 4 of annual ATF Commerce Report
    version: v1
  host: data.atf.gov
  basePath: /resource/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    importation-applications.json:
      get:
        summary: Importation Applications
        description: Importation Applications
        operationId: ""
        parameters:
        - in: query
          name: fiscal_year
          type: string
          format: string
        - in: query
          name: licensed_importer
          type: string
          format: string
        - in: query
          name: military
          type: string
          format: string
        - in: query
          name: other
          type: string
          format: string
        responses:
          200:
            description: Successful response
        tags:
        - firearms
        - ' guns'
        security: []
  definitions: []