- swagger: "2.0"
  info:
    title: API for National Firearms Act Firearms Processed By Form Type
    description: API for Exhibit 7 of annual ATF Commerce Report
    version: v1
  host: data.atf.gov
  basePath: /resource/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    national-firearms-act-firearms-processed-by-form-type.json:
      get:
        summary: National Firearms Act Firearms Processed By Form Type
        description: National Firearms Act Firearms Processed By Form Type
        operationId: ""
        parameters:
        - in: query
          name: application_for_taxpaid_transfer_atf_form_4
          type: string
          format: string
        - in: query
          name: application_for_tax_exempt_transfer_3_atf_form_5
          type: string
          format: string
        - in: query
          name: application_for_tax_exempt_transfer_between_licensees_atf_form_3
          type: string
          format: string
        - in: query
          name: application_to_make_nfa_firearms_atf_form_1
          type: string
          format: string
        - in: query
          name: calendar_year
          type: string
          format: string
        - in: query
          name: exported_atf_form_9
          type: string
          format: string
        - in: query
          name: manufactured_and_imported_atf_form_2
          type: string
          format: string
        responses:
          200:
            description: Successful response
        tags:
        - firearms
        - ' guns'
        security: []
  definitions: []