- swagger: "2.0"
  info:
    title: API for Federal Firearms Licensees And Compliance Inspections
    description: Based on Exhibit 13 on annual Commerce Report.
    version: v1
  host: data.atf.gov
  basePath: /resource/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    ffl-compliance-inspections.json:
      get:
        summary: Federal Firearms Licensees And Compliance Inspections
        description: Federal Firearms Licensees And Compliance Inspections
        operationId: ""
        parameters:
        - in: query
          name: fiscal_year
          type: string
          format: string
        - in: query
          name: inspected
          type: string
          format: string
        - in: query
          name: inspections
          type: string
          format: string
        - in: query
          name: licensees
          type: string
          format: string
        responses:
          200:
            description: Successful response
        tags:
        - firearms
        - ' guns'
        security: []
  definitions: []