- swagger: "2.0"
  info:
    title: API for Pistols - Firearms Manufacturing Report
    description: API for Firearms Manufacturing Report related to pistol manufacturing
    version: v1
  host: data.atf.gov
  basePath: /resource/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    pistols-firearms-manufacturing-report.json:
      get:
        summary: Pistol Manufacturing Report
        description: Pistol Manufacturing Report
        operationId: ""
        parameters:
        - in: query
          name: license_name
          type: string
          format: string
        - in: query
          name: premise_city
          type: string
          format: string
        - in: query
          name: premise_location
          type: string
          format: string
        - in: query
          name: premise_state
          type: string
          format: string
        - in: query
          name: premise_street
          type: string
          format: string
        - in: query
          name: pstl_22_sum
          type: string
          format: string
        - in: query
          name: pstl_25_sum
          type: string
          format: string
        - in: query
          name: pstl_32_sum
          type: string
          format: string
        - in: query
          name: pstl_380_sum
          type: string
          format: string
        - in: query
          name: pstl_50_sum
          type: string
          format: string
        - in: query
          name: pstl_totl_sum
          type: string
          format: string
        - in: query
          name: rds_key
          type: string
          format: string
        - in: query
          name: year
          type: string
          format: string
        responses:
          2:
            description: Successful response
        tags:
        - firearms
        - ' guns'
        - ' pistols'
        security: []
  definitions: []