- swagger: "2.0"
  info:
    title: API for Firearms Imported Into The United States By Country
    description: API for Exhibit 5 of annual ATF Commerce Report
    version: v1
  host: data.atf.gov
  basePath: /resource/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    firearms-imported-into-the-united-states-by-country.json:
      get:
        summary: Firearms Imported Into The United States By Country
        description: Firearms Imported Into The United States By Country
        operationId: ""
        parameters:
        - in: query
          name: country
          type: string
          format: string
        - in: query
          name: handguns
          type: string
          format: string
        - in: query
          name: rifles
          type: string
          format: string
        - in: query
          name: shotguns
          type: string
          format: string
        responses:
          2:
            description: Successful response
        tags:
        - firearms
        - ' guns'
        security: []
  definitions: []