- swagger: "2.0"
  info:
    title: Aspose.Storage API
    description: The Aspose for Cloud File Storage API let's you upload and download
      files for use with our Product APIs
    termsOfService: http://www.aspose.com/corporate/legal/terms-of-use.aspx
    version: v1.1
  host: api.aspose.com
  basePath: /v1.1
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /storage/disc:
      get:
        summary: Get Disc
        description: The resource represents information about users application disc
          usage (size in bytes
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - Get Disc
        security: []
    /storage/exist/{path}:
      get:
        summary: Exist
        description: The controller checks that the file or folder exists in the service
          file storage.
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - Exist
        security: []
    /storage/file/{path}:
      delete:
        summary: Delete File
        description: The resource represents customers file at server file sto
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - File
        security: []
      get:
        summary: Get File
        description: The resource represents customers file at server file storage.
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - File
        security: []
      post:
        summary: Add File
        description: The resource represents customers file at server file storage
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - File
        security: []
      put:
        summary: Put File
        description: The resource represents customers file at server file storage.
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - File
        security: []
    /storage/folder/{folder}:
      delete:
        summary: Delete Folder
        description: 'The resource represents customer folder at service file storage. '
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - Folder
        security: []
      get:
        summary: Get Folder
        description: 'The resource represents customer folder at service file storage. '
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - Folder
        security: []
      post:
        summary: Add Folder
        description: 'The resource represents customer folder at service file storage. '
        operationId: ""
        parameters:
        - in: query
          name: dest
          description: Moves (renames) the file to NewFile.txt
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - Folder
        security: []
  definitions: []