name: Kubernetes
description: Manage a cluster of Linux containers as a single system to accelerate
  Dev and simplify Ops. Kubernetes is an open source orchestration system for Docker
  containers. It handles scheduling onto nodes in a compute cluster and actively manages
  workloads to ensure that their state matches the users declared intentions. Using
  the concepts of labels and pods, it groups the containers which make up an application
  into logical units for easy management and discovery.
image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/kubernetes-logo.png
tags:
- Stack Network
- Google
- Containers
- Container
created: "2017-05-03"
modified: "2017-05-03"
url: https://raw.githubusercontent.com/api-stack/api-stack/gh-pages/_data/api-commons/kubernetes/apis.yaml
specificationVersion: "0.14"
apis:
- name: Kubernetes
  description: Manage a cluster of Linux containers as a single system to accelerate
    Dev and simplify Ops
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/kubernetes-logo.png
  humanURL: http://kubernetes.io
  baseURL: http://kubernetes.io
  tags:
  - Stack Network
  properties:
  - type: x-openapi-spec
    url: https://raw.githubusercontent.com/api-stack/api-stack/gh-pages/_data/api-commons/kubernetes/kubernetes-openapi-spec.yaml
x-common:
- type: x-blog
  url: http://blog.kubernetes.io/
- type: x-blog-rss-feed
  url: http://blog.kubernetes.io/feeds/posts/default
- type: x-github
  url: https://github.com/kubernetes
- type: x-twitter
  url: https://twitter.com/kubernetesio
- type: x-website
  url: http://kubernetes.io/
include: []
maintainers:
- FN: Kin Lane
  x-twitter: apievangelist
  email: info@apievangelist.com