agger: "2.0"
info:
  title: Instructure Canvas Courses API
  description: 'Canvas LMS includes a REST API for accessing and modifying data externally
    from the main application, in your own programs and scripts. '
  termsOfService: https://www.canvaslms.com/policies/api-policy
  version: v1
host: canvas.instructure.com
basePath: /api/v1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []