- swagger: "2.0"
  info:
    title: Fitbit Device API
    description: The Fitbit API allows developers to interact with Fitbit data in their
      own applications, products and services.
    version: "1"
  host: api.fitbit.com
  basePath: /1
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /user/-/devices.{format}:
      get:
        summary: Update Food Goals
        description: Update Food Goals
        operationId: update-food-goals
        parameters:
        - in: query
          name: format
          type: string
        - in: path
          name: format
          type: string
        responses:
          200:
            description: OK
        tags:
        - food
        security: []
  definitions: []