- swagger: "2.0"
  info:
    title: Bitly User Metrics API
    description: The Bitly User Metrics API
    termsOfService: http://dev.bitly.com/best_practices.html
    version: v3
  host: api-ssl.bitly.com
  basePath: /v3
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v3/user/clicks:
      get:
        summary: User Clicks
        description: Returns the aggregate number of clicks on all of the authenticated
          users Bitlinks.
        operationId: userClicks
        parameters:
        - in: query
          name: format
          description: 'json, xml, txt. Default: json.'
          type: string
          format: string
        - in: query
          name: limit
          description: 1 to 1000 (default=100).
          type: integer
          format: integer
        - in: query
          name: rollup
          description: Return data for multiple units rolled up to a single result instead
            of a separate value for each period of time.
          type: boolean
          format: boolean
        - in: query
          name: timezone
          description: 'an integer hour offset from UTC (-14 to 14), or a timezone string
            default: America/New_York.'
          type: string
          format: string
        - in: query
          name: unit
          description: 'minute, hour, day, week or month, default: day '
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for. Pass
            -1 to return all units of time.
          type: integer
          format: integer
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics, default: now. '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/countries:
      get:
        summary: User Countries
        description: Returns aggregate metrics about the countries referring click traffic
          to all of the authenticated users Bitlinks.
        operationId: userCountries
        parameters:
        - in: query
          name: limit
          description: 1 to 1000 (default=100).
          type: integer
          format: integer
        - in: query
          name: rollup
          description: Return data for multiple units rolled up to a single result instead
            of a separate value for each period of time.
          type: boolean
          format: boolean
        - in: query
          name: timezone
          description: 'an integer hour offset from UTC (-14 to 14), or a timezone string
            default: America/New_York.'
          type: string
          format: string
        - in: query
          name: unit
          description: 'minute, hour, day, week or month, default: day '
          type: string
          format: string
        - in: query
          name: units
          description: Successful response
          type: integer
          format: integer
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics, default: now. '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/popular_earned_by_clicks:
      get:
        summary: User Popular Earned By Clicks
        description: Returns the top links to your tracking domain (or domains) created
          by users not associated with your account, ordered by clicks.
        operationId: userPopularEarnedbyClicks
        parameters:
        - in: query
          name: domain
          description: a tracking domain as returned from /v3/user/tracking_domain_list.
          type: string
          format: string
        - in: query
          name: limit
          description: 1..1000 (default=100)
          type: integer
          format: integer
        - in: query
          name: timezone
          description: an integer hour offset from UTC (-14..14), or a timezone string.
            default:America/New_York
          type: string
          format: string
        - in: query
          name: unit
          description: hour | day | week | month default:day
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for.
          type: integer
          format: integer
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics. default:now '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/popular_earned_by_shortens:
      get:
        summary: User Popular Earned By Shortens
        description: Returns the top links to your tracking domain (or domains) created
          by users not associated with your account, ordered by shortens.
        operationId: userPopularEarnedByShortens
        parameters:
        - in: query
          name: domain
          description: a tracking domain as returned from /v3/user/tracking_domain_list.
          type: string
          format: string
        - in: query
          name: limit
          description: 1..1000 (default=100)
          type: string
          format: string
        - in: query
          name: timezone
          description: an integer hour offset from UTC (-14..14), or a timezone string.
            default:America/New_York.
          type: string
          format: string
        - in: query
          name: unit
          description: hour | day | week | month default:day
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics. default:now '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/popular_links:
      get:
        summary: User Popular Links
        description: Returns the authenticated users most-clicked Bitlinks (ordered
          by number of clicks) in a given time period.
        operationId: userPopularLinks
        parameters:
        - in: query
          name: limit
          description: 1..1000 (default=100)
          type: integer
          format: integer
        - in: query
          name: timezone
          description: an integer hour offset from UTC (-14..14), or a timezone string
            default:America/New_York.
          type: string
          format: string
        - in: query
          name: unit
          description: 'minute | hour | day | week | month default:day '
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for. pass
            -1 to return all units of time.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics. default:now '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/popular_owned_by_clicks:
      get:
        summary: User Popular Owned By Clicks
        description: Returns the top links to your tracking domain (or domains) created
          by you or your subaccounts ordered by clicks.
        operationId: userPopularOwnedByClicks
        parameters:
        - in: query
          name: domain
          description: a tracking domain as returned from /v3/user/tracking_domain_list
            (may be specified multiple times).
          type: string
          format: string
        - in: query
          name: limit
          description: 1..1000 (default=100)
          type: integer
          format: integer
        - in: query
          name: subaccount
          description: restrict to links created by this subaccount (may be specified
            multiple times).
          type: string
          format: string
        - in: query
          name: timezone
          description: an integer hour offset from UTC (-14..14), or a timezone string.
            default:America/New_York.
          type: string
          format: string
        - in: query
          name: unit
          description: hour | day | week | month default:day
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics. default:now '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/popular_owned_by_shortens:
      get:
        summary: User Popular Owned by Shortens
        description: Returns the top links to your tracking domain (or domains) created
          by you or your subaccounts ordered by number of shortens.
        operationId: userPopularOwnedByShortens
        parameters:
        - in: query
          name: domain
          description: a tracking domain as returned from /v3/user/tracking_domain_list
            (may be specified multiple times).
          type: string
          format: string
        - in: query
          name: limit
          description: 1..1000 (default=100)
          type: integer
          format: integer
        - in: query
          name: subaccount
          description: restrict to links created by this subaccount (may be specified
            multiple times).
          type: string
          format: string
        - in: query
          name: timezone
          description: an integer hour offset from UTC (-14..14), or a timezone string.
            default:America/New_York
          type: string
          format: string
        - in: query
          name: unit
          description: hour | day | week | month default:day
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics. default:now '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/referrers:
      get:
        summary: User Referrers
        description: Returns aggregate metrics about the pages referring click traffic
          to all of the authenticated users Bitlinks.
        operationId: userReferrers
        parameters:
        - in: query
          name: limit
          description: 1 to 1000 (default=100).
          type: integer
          format: integer
        - in: query
          name: rollup
          description: Return data for multiple units rolled up to a single result instead
            of a separate value for each period of time.
          type: boolean
          format: boolean
        - in: query
          name: timezone
          description: 'an integer hour offset from UTC (-14 to 14), or a timezone string
            default: America/New_York.'
          type: string
          format: string
        - in: query
          name: unit
          description: 'minute, hour, day, week or month, default: day '
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for. Pass
            -1 to return all units of time.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics, default: now. '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/referring_domains:
      get:
        summary: User Referring Domains
        description: eturns aggregate metrics about the domains referring click traffic
          to all of the authenticated users Bitlinks. If the user is a master account,
          or is a subaccount with full_reports permission, the user may choose to view
          the metrics of any account belonging to the master account.
        operationId: userReferringDomains
        parameters:
        - in: query
          name: exclude_social_networks
          description: If true, exclude domains that are part of a social network that
            bitly tracks (default=true).
          type: boolean
          format: boolean
        - in: query
          name: limit
          description: 1 to 1000 (default=100).
          type: integer
          format: integer
        - in: query
          name: login
          description: an optional string consisting of the account name used to report
            the appropriate statistics; defaults to the current user.
          type: string
          format: string
        - in: query
          name: rollup
          description: Return data for multiple units rolled up to a single result instead
            of a separate value for each period of time.
          type: string
          format: string
        - in: query
          name: timezone
          description: 'an integer hour offset from UTC (-14 to 14), or a timezone string
            default: America/New_York.'
          type: string
          format: string
        - in: query
          name: unit
          description: 'minute, hour, day, week or month, default: day '
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for. Pass
            -1 to return all units of time.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics, default: now. '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
    /v3/user/shorten_counts:
      get:
        summary: User Shorten Counts
        description: Returns the number of Bitlinks created in a given time period by
          the authenticated user.
        operationId: userShortenCounts
        parameters:
        - in: query
          name: format
          description: 'json, xml, txt. Default: json.'
          type: string
          format: string
        - in: query
          name: limit
          description: 1 to 1000 (default=100).
          type: integer
          format: integer
        - in: query
          name: rollup
          description: Return data for multiple units rolled up to a single result instead
            of a separate value for each period of time.
          type: boolean
          format: boolean
        - in: query
          name: timezone
          description: 'an integer hour offset from UTC (-14 to 14), or a timezone string
            default: America/New_York.'
          type: string
          format: string
        - in: query
          name: unit
          description: 'minute, hour, day, week or month, default: day '
          type: string
          format: string
        - in: query
          name: units
          description: an integer representing the time units to query data for. Pass
            -1 to return all units of time.
          type: string
          format: string
        - in: query
          name: unit_reference_ts
          description: 'an epoch timestamp, indicating the most recent time for which
            to pull metrics, default: now. '
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - User Metrics
        security: []
  definitions: []