title:        API Stack
url:          http://theapistack.com
logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-stack-logo.jpg
logo_width:   50
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

categories_path : /categories.html
tags_path : /tags.html

# Masthead title
masthead_link: http://theapistack.com
masthead_font_size: 65
masthead_title: '{"API Stack"}'

# Feature
feature_title: API Guide
feature_link: http://apievangelist.com
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/api-guides-loading.jpg
feature_image_width: 40

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-design.png
project_summary: Research project to keep track of established, and emerging best practices around API design. I am also working to include information about the design practices used by leading practioners across the space. You can find news I've curated, organizations doing interesting things, some of the common building blocks I've identified, and open source tooling in this research repo.

# Navigation
navigation:
  - label1: Home
    link1: /
    size1: 70
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 15
    decorate: 0
  - label1: Life Cycle
    link1: /lifecycle/
    size1: 70
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Stack
    link1: /stack/
    size1: 70
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Certifying
    link1: /certifying/
    size1: 70
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: APIs.guru
    link1: http://apis.how/1tcrbzaipy
    size1: 70
    extend: 1
    label2: Github
    link2: https://github.com/APIs-guru/api-models/tree/master/APIs
    size2: 0
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 70
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 15
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 3
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json

# support
support_title: Support My API Stack Research
support_header: I depend on the support of my partners to fund my work as an independent analysts. I have been monitoring the world of APIs since July of 2010 through the support of my partners, and a handful of writing or consulting projects along the way. If you find what I do valuable, please help support me by purchasing my guides, giving below, or if you are need of API definitions created for specific 3rd party, or your own APIs, let me know..
support_footer: I pay my bills by consulting on API projects, and writing white papers and guides. You can find much of my research freely available across my website(s). Anyone who gives $250.00 or more a month, will automatically get access to all of my content via a shared Dropbox, Google Drive, or Github repository. Thank you for your support, and feel free to ping me directly if you have more questions.
