- swagger: "2.0"
  info:
    title: Amazon EC2 VM Export API
    description: The API for management VM Export
    termsOfService: https://aws.amazon.com/terms/
    version: ~
  host: ec2.amazonaws.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /?Action=CancelExportTask&k=1:
      get:
        summary: Cancels an active export task.
        description: Cancels an active export task.
        operationId: cancelexporttask
        parameters:
        - in: query
          name: ExportTaskId
          description: The ID of the export task. This is the ID     returned by CreateInstanceExportTask.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=CreateInstanceExportTask&k=1:
      get:
        summary: Exports a running or stopped instance to an S3 bucket.
        description: Exports a running or stopped instance to an S3 bucket.
        operationId: createinstanceexporttask
        parameters:
        - in: query
          name: Description
          description: A description for the conversion task or the resource being    exported.
            The maximum length is 255 bytes.
          type: string
        - in: query
          name: ExportToS3
          description: The format and location for an instance export task.
          type: string
        - in: query
          name: InstanceId
          description: The ID of the instance.
          type: string
        - in: query
          name: TargetEnvironment
          description: The target virtualization environment.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=DescribeExportTasks&k=1:
      get:
        summary: Describes one or more of your export tasks.
        description: Describes one or more of your export tasks.
        operationId: describeexporttasks
        parameters:
        - in: query
          name: ExportTaskId.N
          description: One or more export task IDs.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []