- swagger: "2.0"
  info:
    title: Amazon RDS Events API
    description: The API for managing Amazon RDS Eventss
    termsOfService: https://aws.amazon.com/terms/
    version: ~
  host: rds.us-east-1.amazonaws.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /?Action=CreateEventSubscription&k=1:
      get:
        summary: Creates an RDS event notification subscription.
        description: Creates an RDS event notification subscription.
        operationId: createeventsubscription
        parameters:
        - in: query
          name: Enabled
          description: A Boolean value; set to true to activate the subscription, set
            to false to create the subscription but not active it.
          type: string
        - in: query
          name: EventCategories.member.N
          description: A list of event categories for a SourceType that you want to
            subscribe to. You can see a list of the categories for a given SourceType             in
            the Events topic in the Amazon RDS User Guide              or by using the
            DescribeEventCategories action.
          type: string
        - in: query
          name: SnsTopicArn
          description: The Amazon Resource Name (ARN) of the SNS topic created for event
            notification. The ARN is created by Amazon SNS when you create             a
            topic and subscribe to it.
          type: string
        - in: query
          name: SourceIds.member.N
          description: The list of identifiers of the event sources for which events
            will be returned. If not specified,            then all sources are included
            in the response. An identifier must begin with a letter and must contain
            only             ASCII letters, digits, and hyphens; it cannot end with
            a hyphen or contain two consecutive hyphens.
          type: string
        - in: query
          name: SourceType
          description: The type of source that will be generating the events. For example,
            if you want to be notified of events generated by a DB instance,             you
            would set this parameter to db-instance. if this value is not specified,
            all events are returned.
          type: string
        - in: query
          name: SubscriptionName
          description: The name of the subscription.
          type: string
        - in: query
          name: Tags.member.N
          description: A list of tags.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=DeleteEventSubscription&k=1:
      get:
        summary: Deletes an RDS event notification subscription.
        description: Deletes an RDS event notification subscription.
        operationId: deleteeventsubscription
        parameters:
        - in: query
          name: SubscriptionName
          description: The name of the RDS event notification subscription you want
            to delete.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=DescribeEventCategories&k=1:
      get:
        summary: Displays a list of categories for all event source types, or, if specified,
          for a specified source type.
        description: Displays a list of categories for all event source types, or, if
          specified, for a specified source type.
        operationId: describeeventcategories
        parameters:
        - in: query
          name: Filters.member.N
          description: This parameter is not currently supported.
          type: string
        - in: query
          name: SourceType
          description: The type of source that will be generating the events.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=DescribeEvents&k=1:
      get:
        summary: Returns events related to DB instances, DB security groups, DB snapshots,
          and DB parametern        groups for the past 14 days.
        description: Returns events related to DB instances, DB security groups, DB
          snapshots, and DB parametern        groups for the past 14 days.
        operationId: describeevents
        parameters:
        - in: query
          name: Duration
          description: The number of minutes to retrieve events for.
          type: string
        - in: query
          name: EndTime
          description: The end of the time interval for which to retrieve events,        specified
            in ISO 8601 format. For more information about ISO 8601,         go to the
            ISO8601 Wikipedia page.
          type: string
        - in: query
          name: EventCategories.member.N
          description: A list of event categories that trigger notifications for a event
            notification subscription.
          type: string
        - in: query
          name: Filters.member.N
          description: This parameter is not currently supported.
          type: string
        - in: query
          name: Marker
          description: An optional pagination token provided by a previous        DescribeEvents
            request.        If this parameter is specified, the response includes        only
            records beyond the marker,        up to the value specified by MaxRecords.
          type: string
        - in: query
          name: MaxRecords
          description: The maximum number of records to include in the response.        If
            more records exist than the specified MaxRecords value,            a pagination
            token called a marker is included in the response so that the remaining        results
            can be retrieved.
          type: string
        - in: query
          name: SourceIdentifier
          description: The identifier of the event source for which events        will
            be returned. If not specified,        then all sources are included in the
            response.
          type: string
        - in: query
          name: SourceType
          description: The event source to retrieve events for.        If no value is
            specified, all events are returned.
          type: string
        - in: query
          name: StartTime
          description: The beginning of the time interval to retrieve events for,        specified
            in ISO 8601 format. For more information about ISO 8601,         go to the
            ISO8601 Wikipedia page.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=DescribeEventSubscriptions&k=1:
      get:
        summary: Lists all the subscription descriptions for a customer account.
        description: Lists all the subscription descriptions for a customer account.
        operationId: describeeventsubscriptions
        parameters:
        - in: query
          name: Filters.member.N
          description: This parameter is not currently supported.
          type: string
        - in: query
          name: Marker
          description: An optional pagination token provided by a previous            DescribeOrderableDBInstanceOptions
            request.            If this parameter is specified, the response includes            only
            records beyond the marker,            up to the value specified by MaxRecords
            .
          type: string
        - in: query
          name: MaxRecords
          description: The maximum number of records to include in the response.            If
            more records exist than the specified MaxRecords value,            a pagination
            token called a marker is included in the response so that the remaining            results
            can be retrieved.
          type: string
        - in: query
          name: SubscriptionName
          description: The name of the RDS event notification subscription you want
            to describe.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /?Action=ModifyEventSubscription&k=1:
      get:
        summary: Modifies an existing RDS event notification subscription.
        description: Modifies an existing RDS event notification subscription.
        operationId: modifyeventsubscription
        parameters:
        - in: query
          name: Enabled
          description: A Boolean value; set to true to activate the subscription.
          type: string
        - in: query
          name: EventCategories.member.N
          description: A list of event categories for a SourceType that you want to
            subscribe to. You can see a list of the categories for a given SourceType             in
            the Events topic in the Amazon RDS User Guide              or by using the
            DescribeEventCategories action.
          type: string
        - in: query
          name: SnsTopicArn
          description: The Amazon Resource Name (ARN) of the SNS topic created for event
            notification. The ARN is created by Amazon SNS when you create             a
            topic and subscribe to it.
          type: string
        - in: query
          name: SourceType
          description: The type of source that will be generating the events. For example,
            if you want to be notified of events generated by a DB instance,             you
            would set this parameter to db-instance. if this value is not specified,
            all events are returned.
          type: string
        - in: query
          name: SubscriptionName
          description: The name of the RDS event notification subscription.
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []