- swagger: "2.0"
  info:
    title: Facebook Graph (Application) API
    description: API for managing Facebook Applications
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /application/accounts:
      get:
        summary: Get Application Account
        description: Facebook App
        operationId: application
        responses:
          200:
            description: OK
        tags:
        - applications
        security: []
    /{application-id}:
      get:
        summary: Get Application
        description: Facebook App
        operationId: application
        responses:
          200:
            description: OK
        tags:
        - applications
        security: []
    /{application_id}:
      get:
        summary: Get Application
        description: Facebook App
        operationId: application
        responses:
          200:
            description: OK
        tags:
        - applications
        security: []
    /{page_id}:
      get:
        summary: Get Page
        description: Facebook App
        operationId: application
        responses:
          200:
            description: OK
        tags:
        - applications
        security: []
  definitions: []