- swagger: "2.0"
  info:
    title: Facebook Graph (App Request) API
    description: API for managing Facebook App Requests
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{app-request-id}:
      get:
        summary: App Request
        description: App Request
        operationId: app-request
        responses:
          200:
            description: OK
        tags:
        - applications
        security: []
    /{app_request_id}:
      get:
        summary: App Request
        description: App Request
        operationId: app-request
        responses:
          200:
            description: OK
        tags:
        - applications
        security: []
  definitions: []