- swagger: "2.0"
  info:
    title: Facebook Graph (Profile) API
    description: API for managing Facebook Profiles
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /{profile-id}:
      get:
        summary: 'A profile can be a:'
        description: 'A profile can be a:'
        operationId: profile
        responses:
          200:
            description: OK
        tags:
        - profile
        security: []
  definitions: []