- swagger: "2.0"
  info:
    title: Facebook Graph (Life Event) API
    description: API for managing Facebook Life Events
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{life-event-id}:
      get:
        summary: Life Event
        description: Life Event
        operationId: life-event
        responses:
          200:
            description: OK
        tags:
        - events
        security: []
  definitions: []