- swagger: "2.0"
  info:
    title: Facebook Graph (Application Context) API
    description: API for managing Facebook Application Contexts
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{application-context-id}:
      get:
        summary: Application Context
        description: Application Context
        operationId: application-context
        responses:
          200:
            description: OK
        tags:
        - context
        security: []
  definitions: []