- swagger: "2.0"
  info:
    title: Facebook Graph (Video) API
    description: API for managing Facebook Videos
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /{user-id}/videos:
      get:
        summary: Video
        description: Video
        operationId: video
        responses:
          200:
            description: OK
        tags:
        - videos
        security: []
  definitions: []