- swagger: "2.0"
  info:
    title: Facebook Graph (User) API
    description: API for managing Facebook Users
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /user/adaccountgroups:
      get:
        summary: User
        description: User
        operationId: user
        responses:
          200:
            description: OK
        tags:
        - users
        security: []
    /{ad_account_group_id}:
      get:
        summary: User
        description: User
        operationId: user
        responses:
          200:
            description: OK
        tags:
        - users
        security: []
    /{user-id}:
      get:
        summary: User
        description: User
        operationId: user
        responses:
          200:
            description: OK
        tags:
        - users
        security: []
    /{user_id}:
      get:
        summary: User
        description: User
        operationId: user
        responses:
          200:
            description: OK
        tags:
        - users
        security: []
  definitions: []