- swagger: "2.0"
  info:
    title: Facebook Graph (Offer) API
    description: API for managing Facebook Offers
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /{offer-id}:
      get:
        summary: An offer that is published by a Facebook Page
        description: An offer that is published by a Facebook Page
        operationId: offer
        responses:
          200:
            description: OK
        tags:
        - offers
        security: []
    /{page-id}/offers:
      get:
        summary: An offer that is published by a Facebook Page
        description: An offer that is published by a Facebook Page
        operationId: offer
        responses:
          200:
            description: OK
        tags:
        - offers
        security: []
  definitions: []