- swagger: "2.0"
  info:
    title: Facebook Graph (Open Graph Context) API
    description: API for managing Facebook Open Graph Contexts
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{open-graph-context-id}:
      get:
        summary: Open Graph Context
        description: Open Graph Context
        operationId: open-graph-context
        responses:
          200:
            description: OK
        tags:
        - graph context
        security: []
  definitions: []