- swagger: "2.0"
  info:
    title: Facebook Graph (Open Graph Action Type) API
    description: API for managing Facebook Open Graph Action Types
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{open-graph-action-type-id}:
      get:
        summary: Open Graph Action Type
        description: Open Graph Action Type
        operationId: open-graph-action-type
        responses:
          200:
            description: OK
        tags:
        - graph actions
        security: []
  definitions: []