- swagger: "2.0"
  info:
    title: Facebook Graph (Open Graph Object Type) API
    description: API for managing Facebook Open Graph Object Types
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{open-graph-object-type-id}:
      get:
        summary: Open Graph Object Type
        description: Open Graph Object Type
        operationId: open-graph-object-type
        responses:
          200:
            description: OK
        tags:
        - graph objects
        security: []
  definitions: []