- swagger: "2.0"
  info:
    title: Facebook Graph (Group Doc) API
    description: API for managing Facebook Group Docs
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{group-doc-id}:
      get:
        summary: Get Group Doc
        description: Represents a doc within a Facebook group
        operationId: group-doc
        parameters:
        - in: query
          name: can_delete
          description: Whether the session user can delete this doc (on Facebook.com).
          type: string
        - in: query
          name: can_edit
          description: Whether the session user can edit this doc.
          type: string
        - in: query
          name: created_time
          description: When the doc was created.
          type: string
        - in: query
          name: from
          description: The profile that created this doc.
          type: string
        - in: query
          name: icon
          description: The URL for the doc&#039;s icon
          type: string
        - in: query
          name: id
          description: The group doc ID.
          type: string
        - in: query
          name: message
          description: The body of the doc. This string will contain HTML for any formatting
            in the doc, and will be HTML encoded.
          type: string
        - in: query
          name: revision
          description: An ID representing the current doc revision.
          type: string
        - in: query
          name: subject
          description: The title of the doc.
          type: string
        - in: query
          name: updated_time
          description: The last time the doc was changed.
          type: string
        responses:
          200:
            description: OK
        tags:
        - groups
        security: []
  definitions: []