- swagger: "2.0"
  info:
    title: Facebook Graph (Video Broadcast) API
    description: API for managing Facebook Video Broadcasts
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{video-broadcast-id}:
      get:
        summary: Video Broadcast
        description: Video Broadcast
        operationId: video-broadcast
        responses:
          200:
            description: OK
        tags:
        - videos
        security: []
  definitions: []