- swagger: "2.0"
  info:
    title: Facebook Graph (Mailing Address) API
    description: API for managing Facebook Mailing Addresss
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{mailing-address-id}:
      get:
        summary: Mailing Address
        description: Mailing Address
        operationId: mailing-address
        responses:
          200:
            description: OK
        tags:
        - mailing address
        security: []
  definitions: []