- swagger: "2.0"
  info:
    title: Facebook Graph (Video List) API
    description: API for managing Facebook Video Lists
    termsOfService: https://www.facebook.com/policies/
    version: ~
  host: graph.facebook.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /v2.5/{video-list-id}:
      get:
        summary: Video List
        description: Video List
        operationId: video-list
        responses:
          200:
            description: OK
        tags:
        - videos
        security: []
    /{video_list_id}:
      get:
        summary: Video List
        description: Video List
        operationId: video-list
        responses:
          200:
            description: OK
        tags:
        - videos
        security: []
  definitions: []