- swagger: "2.0"
  info:
    title: Stack Exchange Suggested Edits API
    description: The API for managing Stack Exchange suggested edits.
    termsOfService: http://stackexchange.com/legal/api-terms-of-use
    version: "2.2"
  host: api.stackexchange.com
  basePath: /2.2
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /suggested-edits:
      get:
        summary: Get all the suggested edits on the site.
        description: Get all the suggested edits on the site.
        operationId: ""
        parameters:
        - in: query
          name: fromdate
          type: string
          format: string
        - in: query
          name: max
          type: string
          format: string
        - in: query
          name: min
          type: string
          format: string
        - in: query
          name: order
          type: string
          format: string
        - in: query
          name: page
          type: string
          format: string
        - in: query
          name: pagesize
          type: string
          format: string
        - in: query
          name: sort
          type: string
          format: string
        - in: query
          name: todate
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - Suggested Edits
        security: []
    /suggested-edits/{ids}:
      get:
        summary: Get the suggested edits identified by a set of ids.
        description: Get the suggested edits identified by a set of ids.
        operationId: ""
        parameters:
        - in: query
          name: fromdate
          type: string
          format: string
        - in: path
          name: ids
          type: string
          format: string
        - in: query
          name: max
          type: string
          format: string
        - in: query
          name: min
          type: string
          format: string
        - in: query
          name: order
          type: string
          format: string
        - in: query
          name: page
          type: string
          format: string
        - in: query
          name: pagesize
          type: string
          format: string
        - in: query
          name: sort
          type: string
          format: string
        - in: query
          name: todate
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - Suggested Edits
        security: []
  definitions: []