- swagger: "2.0"
  info:
    title: Alchemy Sentiment Analysis API
    description: AlchemyAPI provides easy-to-use mechanisms to identify positive/negative
      sentiment within any document or web page.
    termsOfService: http://www.alchemyapi.com/company/terms.html
    contact:
      name: AlchemyAPI
      url: http://www.alchemyapi.com/company/contact
      email: questions@alchemyapi.com
    version: v1
  host: access.alchemyapi.com
  basePath: /calls/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /url/URLGetTextSentiment:
      get:
        summary: /calls/url/URLGetTextSentiment
        description: AlchemyAPI provides easy-to-use mechanisms to identify positive/negative
          sentiment within any document or web page.
        operationId: callsUrlURLGetTextSentiment
        parameters:
        - in: query
          name: apikey
          type: string
          format: string
        - in: query
          name: url
          type: string
          format: string
        responses:
          200:
            description: Successful response
            schema:
              type: array
              items:
                $ref: '#/definitions/results'
        tags:
        - Sentiment Analysis
        security:
        - apikey: []
  securityDefinitions:
    apikey:
      type: apiKey
      name: apikey
  definitions:
    results:
      properties:
        status:
          description: This is a default description.
          type: string
        usage:
          description: This is a default description.
          type: string
        url:
          description: This is a default description.
          type: string
        totalTransactions:
          description: This is a default description.
          type: integer
        language:
          description: This is a default description.
          type: string
    docSentiment:
      properties:
        mixed:
          description: This is a default description.
          type: string
        score:
          description: This is a default description.
          type: string
        type:
          description: This is a default description.
          type: string