- swagger: "2.0"
  info:
    title: Spotify Tracks API
    version: ~
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /tracks:
      get:
        summary: ""
        description: '[Get Several Tracks](https://developer.spotify.com/web-api/get-several-tracks/)n'
        operationId: get-several-trackshttpsdeveloperspotifycomwebapigetseveraltracks
        parameters:
        - in: query
          name: ids
          description: A comma-separated list of IDs
        - in: query
          name: market
          description: The market (an ISO 3166-1 alpha-2 country code)
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /tracks/{id}:
      get:
        summary: ""
        description: '[Get a Track](https://developer.spotify.com/web-api/get-track/)n'
        operationId: get-a-trackhttpsdeveloperspotifycomwebapigettrack
        parameters:
        - in: path
          name: id
        - in: query
          name: market
          description: The market (an ISO 3166-1 alpha-2 country code)
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []