- swagger: "2.0"
  info:
    title: LinkedIn Groups API
    version: ""
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /groups/{group-id}:
      get:
        summary: Get Group
        description: Get Group
        operationId: get-group
        parameters:
        - in: path
          name: group-id
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /groups/{group-id}/posts:
      get:
        summary: Get Group Posts
        description: Get Group Posts
        operationId: get-group-posts
        parameters:
        - in: path
          name: group-id
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      post:
        summary: Create Group Post
        description: Create Group Post
        operationId: create-group-post
        parameters:
        - in: path
          name: group-id
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []