- swagger: "2.0"
  info:
    title: Wikipedia
    description: This API aims to provide straightforward and low-latency access to
      Wikimedia content and services. It is currently in beta testing, so things aren't
      completely locked down yet. Each entry point has explicit stability markers to
      inform you about development status and change policy, according to our API version
      policy.
    version: v1
  host: en.wikipedia.org
  basePath: v1/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /page/:
      get:
        summary: 'List page properties / page content sub-apis.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Stable)n'
        description: 'List page properties / page content sub-apis.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Stable)n'
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/data-parsoid/:
      get:
        summary: 'List titles for which the data-parsoid property is available. This
          currently only lists pages which have revisions stored in RESTBase.nStability:
          [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'List titles for which the data-parsoid property is available.
          This currently only lists pages which have revisions stored in RESTBase.nStability:
          [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/data-parsoid/{title}:
      get:
        summary: 'Retrieve the latest data-parsoid (private Parsoid metadata)nStability:
          [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'Retrieve the latest data-parsoid (private Parsoid metadata)nStability:
          [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: path
          name: title
          description: the title of page content
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/data-parsoid/{title}/:
      get:
        summary: 'List data-parsoid revisions for a page. This currently only lists
          revisions stored in RESTBase.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'List data-parsoid revisions for a page. This currently only lists
          revisions stored in RESTBase.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/data-parsoid/{title}/{revision}{/tid}:
      get:
        summary: 'Retrieve data-parsoid (internal Parsoid metadata) for a given page
          & revisionnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'Retrieve data-parsoid (internal Parsoid metadata) for a given
          page & revisionnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: path
          name: revision
          description: The revision
          type: string
          format: string
        - in: path
          name: tid
          description: The revisions time ID
          type: string
          format: string
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/html/:
      get:
        summary: 'List titles for which an HTML representation is available. Currently
          this only lists pages that have revisions stored in RESTBase.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)n'
        description: 'List titles for which an HTML representation is available. Currently
          this only lists pages that have revisions stored in RESTBase.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)n'
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/html/{title}:
      get:
        summary: Retrieve the latest html for a page title. nIf you know the revision
          as well, then please use the `{title}/{revision}` end point instead for better
          performance.nSee [the MediaWiki DOM spec](https://www.mediawiki.org/wiki/Parsoid/MediaWiki_DOM_spec)
          f
        description: 'Retrieve the latest html for a page title. nIf you know the revision
          as well, then please use the `{title}/{revision}` end point instead for better
          performance.nSee [the MediaWiki DOM spec](https://www.mediawiki.org/wiki/Parsoid/MediaWiki_DOM_spec)
          for a description of the MediaWiki-specific semantic markup in this HTML.nStability:
          [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: path
          name: title
          description: The page title.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/html/{title}/:
      get:
        summary: 'List HTML revisions for a title. This currently only lists revisions
          that are already stored in RESTBase.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)n'
        description: 'List HTML revisions for a title. This currently only lists revisions
          that are already stored in RESTBase.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)n'
        operationId: ""
        parameters:
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/html/{title}/{revision}{/tid}:
      get:
        summary: 'Retrieve the html for a given revision (and optional timeuuid).nSee
          [the MediaWiki DOM spec](https://www.mediawiki.org/wiki/Parsoid/MediaWiki_DOM_spec)
          for a description of the MediaWiki-specific semantic markup in this HTML.nThis
          HTML can be edited '
        description: 'Retrieve the html for a given revision (and optional timeuuid).nSee
          [the MediaWiki DOM spec](https://www.mediawiki.org/wiki/Parsoid/MediaWiki_DOM_spec)
          for a description of the MediaWiki-specific semantic markup in this HTML.nThis
          HTML can be edited using arbitrary HTML tools. The modified HTML can be converted
          back to wikitext using the [/transform/html/to/wikitext{/title}{/revision}](#!/Transforms/transform_html_to_wikitext__title___revision__post)
          entry point.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: path
          name: revision
          description: The revision
          type: string
          format: string
        - in: path
          name: tid
          description: The revisions time ID
          type: string
          format: string
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/revision/:
      get:
        summary: 'List revisions. This currently only lists revisions stored in RESTBase.nStability:
          [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental).
          Don''t rely on this.n'
        description: 'List revisions. This currently only lists revisions stored in
          RESTBase.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental).
          Dont rely on this.n'
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/revision/{revision}:
      get:
        summary: 'Get metadata about a specific revision.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'Get metadata about a specific revision.nStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: path
          name: revision
          description: The revision id
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/title/:
      get:
        summary: 'List all pages.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental).
          Don''t rely on this.n'
        description: 'List all pages.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental).
          Dont rely on this.n'
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /page/title/{title}/:
      get:
        summary: 'List revisions for a title. Currently this lists all revisions that
          ever used this title and are stored in RESTBase, but eventually it should
          probably return the linear history (across renames) of the page currently
          using this title.nStability: [expe'
        description: 'List revisions for a title. Currently this lists all revisions
          that ever used this title and are stored in RESTBase, but eventually it should
          probably return the linear history (across renames) of the page currently
          using this title.nStability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)n'
        operationId: ""
        parameters:
        - in: path
          name: title
          description: The page title.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /transform/html/to/html{/title}{/revision}:
      post:
        summary: 'Update / refresh / sanitize HTMLnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'Update / refresh / sanitize HTMLnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: formData
          name: bodyOnly
          description: Return only `body.innerHTML`
          type: string
          format: string
        - in: formData
          name: html
          description: The HTML to transform
          type: string
          format: string
        - in: path
          name: revision
          description: The page revision
          type: string
          format: string
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /transform/html/to/wikitext{/title}{/revision}:
      post:
        summary: 'Transform HTML to wikitextnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'Transform HTML to wikitextnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: formData
          name: html
          description: The HTML to transform
          type: string
          format: string
        - in: path
          name: revision
          description: The page revision
          type: string
          format: string
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /transform/wikitext/to/html{/title}{/revision}:
      post:
        summary: 'Transform wikitext to HTMLnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        description: 'Transform wikitext to HTMLnStability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)n'
        operationId: ""
        parameters:
        - in: formData
          name: bodyOnly
          description: Return only `body.innerHTML`
          type: string
          format: string
        - in: path
          name: revision
          description: The page revision
          type: string
          format: string
        - in: path
          name: title
          description: The page title
          type: string
          format: string
        - in: formData
          name: wikitext
          description: The Wikitext to transform to HTML
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions:
    "":
      properties:
        type:
          description: This is a default description.
          type: string
        title:
          description: This is a default description.
          type: string
        detail:
          description: This is a default description.
          type: string
        instance:
          description: This is a default description.
          type: string
        items:
          description: This is a default description.
          type: string
        counter:
          description: This is a default description.
          type: string
        ids:
          description: This is a default description.
          type: string
        count:
          description: This is a default description.
          type: string