- swagger: "2.0"
  info:
    title: API Evangelist API API
    description: This is an API providing access to the APIs I keep an eye on as part
      of the API Evangelist network.
    termsOfService: http://developer.apievangelist.com/index.html
    contact:
      name: Kin Lane
      url: http://kinlane.com
      email: info@apievangelist.com
    license:
      name: MIT
      url: http://opensource.org/licenses/MIT
    version: "1.0"
  host: api.apievangelist.com
  basePath: /v1
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /api/{id}:
      get:
        summary: Retrieve an API
        description: Returns the API detail
        operationId: getAPI
        parameters:
        - in: query
          name: appid
          description: application id for application making calls
          type: string
        - in: query
          name: appkey
          description: application key for application making calls
          type: string
        - in: path
          name: id
          description: id of the blog post to be returned
          type: integer
        responses:
          200:
            description: Successful API Response
            schema:
              type: array
              items:
                $ref: '#/definitions/api'
        tags:
        - ""
        security: []
    /apis:
      get:
        summary: Retrieve APIs
        description: Returns a list of APIs.
        operationId: getAPI
        parameters:
        - in: query
          name: appid
          description: application id for application making calls
          type: string
        - in: query
          name: appkey
          description: application key for application making calls
          type: string
        - in: query
          name: date
          description: data to search by in the m/d/Y format
          type: string
        - in: query
          name: limit
          description: how many posts to show
          type: integer
        - in: query
          name: new
          description: only show new apis (true / false)
          type: string
        - in: query
          name: query
          description: a text query to search across posts
          type: string
        responses:
          200:
            description: Successful API Response
            schema:
              type: array
              items:
                $ref: '#/definitions/api'
        tags:
        - ""
        security: []
  definitions:
    API:
      properties:
        API_ID:
          description: This is a default description.
          type: string
        Launch_Date:
          description: This is a default description.
          type: string
        Name:
          description: This is a default description.
          type: string
        About:
          description: This is a default description.
          type: string
        URL:
          description: This is a default description.
          type: string
    Error:
      properties:
        code:
          description: This is a default description.
          type: integer
        message:
          description: This is a default description.
          type: string
        fields:
          description: This is a default description.
          type: string