- swagger: "2.0"
  info:
    title: API Evangelist - Road Map API
    description: I try to make sure I share what I am planning for each API self contained
      within each project repository. I use the Github issues management for organizing
      my road map, issues, and road map. This is just a static cache of the Github issues
      for this project.
    termsOfService: http://kinlane.com/terms-of-service.html
    version: v1
  host: road-map.api.apievangelist.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /road-map/:
      get:
        summary: Get Road Map
        description: retrieves all road map entries
        operationId: getRoadMap
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: host
          description: host for the road map entry
        - in: query
          name: query
          description: a text query to search across road map entries
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
      post:
        summary: Add Road Map
        description: add road map
        operationId: addChangeLog
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: footer
          description: footer for the road map entry
        - in: query
          name: header
          description: header for the road map entry
        - in: query
          name: host
          description: host of the road map entry
        - in: query
          name: image
          description: image for the road map entry
        - in: query
          name: title
          description: title of the road map entry
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
    /road-map/{host}/:
      get:
        summary: Get Road Map by Host
        description: retrieves all road_map entries by host
        operationId: getRoad Map
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: host
          description: host for the road map entry
        - in: query
          name: query
          description: a text query to search across road map entries
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
    /road-map/{host}/default/:
      post:
        summary: Set Default Road Map For Host
        description: set default road map for host
        operationId: setDefaultChangeLogForHost
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: description
          description: description for the road map entry key
        - in: query
          name: name
          description: name of the road map entry key
        - in: query
          name: road_map_id
          description: unique id of the road map entry
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
    /road-map/{road_map_id}/:
      delete:
        summary: Delete Road Map
        description: delete an road map entry
        operationId: deleteChangeLog
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: host
          description: host for the road map entry
        - in: path
          name: road_map_id
          description: id for the road map entry
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
      get:
        summary: Get Road Map
        description: retrieve a specific road map entry
        operationId: getChangeLogEntry
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: path
          name: road_map_id
          description: id for the road map entry
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
      put:
        summary: Update Road Map
        description: update an road map entry
        operationId: updateChangeLog
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: footer
          description: footer for the road map entry
        - in: query
          name: header
          description: header for the road map entry
        - in: query
          name: host
          description: host for the road map entry
        - in: query
          name: image
          description: image for the road map entry
        - in: query
          name: title
          description: title of the road map entry
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
    /road-map/{road_map_id}/history/:
      post:
        summary: Add Road Map History
        description: Add road map key
        operationId: addChangeLogKey
        parameters:
        - in: query
          name: appid
          description: your appid for accessing the API
        - in: query
          name: appkey
          description: your appkey for accessing the API
        - in: query
          name: description
          description: description for the road map entry key
        - in: query
          name: name
          description: name of the road map entry key
        - in: query
          name: road_map_id
          description: unique id of the road map entry
        responses:
          200:
            description: OK
        tags:
        - Road Map
        security: []
  definitions:
    road_map:
      properties:
        road_map_id:
          description: This is a default description.
          type: get
        title:
          description: This is a default description.
          type: get
        image:
          description: This is a default description.
          type: get
        header:
          description: This is a default description.
          type: get
        footer:
          description: This is a default description.
          type: get
        keys:
          description: This is a default description.
          type: get
    keys:
      properties:
        key_id:
          description: This is a default description.
          type: get
        name:
          description: This is a default description.
          type: get
        description:
          description: This is a default description.
          type: get
        road_map_id:
          description: This is a default description.
          type: get