- swagger: "2.0"
  info:
    title: Eventbrite System API
    description: The API for managing the Eventbrite system.
    version: v3
  host: www.eventbriteapi.com
  basePath: /v3
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /system/timezones/:
      'get ':
        summary: Returns a paginated response with a key of timezones,ncontaining a
          list of timezones.
        description: Returns a paginated response with a key of timezones,ncontaining
          a list of timezones.
        operationId: returns-a-paginated-response-with-a-key-of-timezonescontaining-a-list-of-timezones
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []