- name: Docker
  description: Docker is an open platform for developers and sysadmins to build, ship,
    and run distributed applications. Consisting of Docker Engine, a portable, lightweight
    runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
    and automating workflows, Docker enables apps to be quickly assembled from components
    and eliminates the friction between development, QA, and production environments.
    As a result, IT can ship faster and run the same app, unchanged, on laptops, data
    center VMs, and any cloud.
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
  x-open-ranking: "0"
  tags:
  - API-Stack
  created: "2016-04-20"
  modified: "2016-04-20"
  url: http://theapistack.com/data/docker/apis.json
  specificationVersion: "0.14"
  apis:
  - name: Docker Remote Authentication API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-authentication-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-authentication-api-openapi-spec.yaml
  - name: Docker Remote Build API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-build-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-build-api-openapi-spec.yaml
  - name: Docker Remote Commit API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-commit-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-commit-api-openapi-spec.yaml
  - name: Docker Remote Containers API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-containers-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-containers-api-openapi-spec.yaml
  - name: Docker Remote Events API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-events-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-events-api-openapi-spec.yaml
  - name: Docker Remote Exec API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-exec-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-exec-api-openapi-spec.yaml
  - name: Docker Remote Images API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-images-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-images-api-openapi-spec.yaml
  - name: Docker Remote Info API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-info-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-info-api-openapi-spec.yaml
  - name: Docker Remote Ping API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-ping-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-ping-api-openapi-spec.yaml
  - name: Docker Remote Version API
    description: Docker is an open platform for developers and sysadmins to build, ship,
      and run distributed applications. Consisting of Docker Engine, a portable, lightweight
      runtime and packaging tool, and Docker Hub, a cloud service for sharing applications
      and automating workflows, Docker enables apps to be quickly assembled from components
      and eliminates the friction between development, QA, and production environments.
      As a result, IT can ship faster and run the same app, unchanged, on laptops, data
      center VMs, and any cloud.
    image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/docker.png
    humanURL: ""
    baseURL: ""
    tags:
    - API-Stack
    properties:
    - type: x-openapi-spec-json
      url: http://theapistack.com/data/docker/docker-remote-version-api-openapi-spec.json
    - type: x-openapi-spec-yaml
      url: https://github.com/api-stack/api-stack/blob/gh-pages/_data/docker/docker-remote-version-api-openapi-spec.yaml
  x-common:
  - type: x-blog
    url: http://blog.docker.com/
  - type: x-blog-rss-feed
    url: http://blog.docker.com/feed/
  - type: x-github
    url: https://github.com/docker
  - type: x-twitter
    url: https://twitter.com/docker
  - type: x-webinars
    url: https://www.docker.com/
  include:
  - name: Parent
    url: http://theapistack.com/apis.json
  maintainers:
  - FN: Kin Lane
    x-twitter: apievangelist
    email: info@apievangelist.com