- swagger: "2.0"
  info:
    title: Docker Remote Info API
    description: The API for managing Docker Remote Info
    termsOfService: https://www.docker.com/docker-terms-service
    version: ""
  host: api.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /info:
      get:
        summary: Display system-wide information
        description: Display system-wide information
        operationId: display-systemwide-information
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []