- swagger: "2.0"
  info:
    title: Twilio Queues API
    description: Twilio is a cloud communications Infrastructure as a Service(IaaS)
      company based in San Francisco, California. Twilio allows software developers
      to programmatically make and receive phone calls and send and receive text messages
      using its web service APIs. Twilio's services are accessed over HTTP and are billed
      based on usage.
    termsOfService: https://www.twilio.com/legal/tos
    version: "2010-04-01"
  host: api.twilio.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /Accounts/{AccountSid}/Queues/{QueueSid}/Members/Front{mediaTypeExtension}:
      get:
        summary: Get Queue Members In Front
        description: Get a front member.
        operationId: get-a-front-member
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
      post:
        summary: Update Queue Members In Front
        description: Posting a URL and Method to a Queue instance will dequeue a member
          from anqueue and have the members call begin executing the TwiML document
          at that URLnWhen dequeuing the Front of the queue, the next call in the queue
          will be redirected.n
        operationId: posting-a-url-and-method-to-a-queue-instance-will-dequeue-a-member-from-aqueue-and-have-the-members-
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
    /Accounts/{AccountSid}/Queues/{QueueSid}/Members/{CallSid}{mediaTypeExtension}:
      get:
        summary: Get Queue Members
        description: Get a specific member.
        operationId: get-a-specific-member
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: CallSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
      post:
        summary: Update Queue Members
        description: Posting a URL and Method to a Queue instance will dequeue a member
          from anqueue and have the members call begin executing the TwiML document
          at that URLnWhen redirecting a member of a queue addressed by CallSid, only
          the first requestnwill succeed and return a 200 response code. A second request
          will fail andnreturn an appropriate 400 response code.n
        operationId: posting-a-url-and-method-to-a-queue-instance-will-dequeue-a-member-from-aqueue-and-have-the-members-
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: CallSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
    /Accounts/{AccountSid}/Queues/{QueueSid}/Members{mediaTypeExtension}:
      get:
        summary: Get Queue Members
        description: Returns the list of members in the queue identified by {QueueSid}.
        operationId: returns-the-list-of-members-in-the-queue-identified-by-queuesid
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
    /Accounts/{AccountSid}/Queues/{QueueSid}{mediaTypeExtension}:
      delete:
        summary: Delete Queue Members
        description: The DELETE method allows you to remove a Queue. Only empty queues
          arendeletable.n
        operationId: the-delete-method-allows-you-to-remove-a-queue-only-empty-queues-aredeletable
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
      get:
        summary: Get Queue Members
        description: Get resources individual Queue instance.n
        operationId: get-resources-individual-queue-instance
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
      post:
        summary: Add Queue Members
        description: This POST request allows you to change the FriendlyName or MaxSize.n
        operationId: this-post-request-allows-you-to-change-the-friendlyname-or-maxsize
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        - in: path
          name: QueueSid
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
    /Accounts/{AccountSid}/Queues{mediaTypeExtension}:
      get:
        summary: Get Queues
        description: Returns a list of queues within an account. The list includes pagingninformation.n
        operationId: returns-a-list-of-queues-within-an-account-the-list-includes-paginginformation
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
      post:
        summary: Add Queue
        description: Create a new Queue resource.n
        operationId: create-a-new-queue-resource
        parameters:
        - in: path
          name: AccountSid
        - in: path
          name: mediaTypeExtension
          description: By default, Twilios REST API returns XML. You may obtain CSV,
            JSON or HTML by appending .csv, .json, or .html.n
        responses:
          200:
            description: OK
        tags:
        - queues
        security: []
  definitions: []