- swagger: "2.0"
  info:
    title: Twilio Sandbox API
    description: Twilio is a cloud communications Infrastructure as a Service(IaaS)
      company based in San Francisco, California. Twilio allows software developers
      to programmatically make and receive phone calls and send and receive text messages
      using its web service APIs. Twilio's services are accessed over HTTP and are billed
      based on usage.
    termsOfService: https://www.twilio.com/legal/tos
    version: "2010-04-01"
  host: api.twilio.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /{AccountSid}/Sandbox.{format}:
      get:
        summary: GetSandbox
        description: GetSandbox
        operationId: getsandbox
        parameters:
        - in: path
          name: AccountSid
          type: string
        - in: path
          name: format
          type: string
        responses:
          200:
            description: OK
        tags:
        - sandbox
        security: []
      post:
        summary: UpdateSandbox
        description: UpdateSandbox (POST)
        operationId: updatesandbox-post
        parameters:
        - in: path
          name: AccountSid
          type: string
        - in: path
          name: format
          type: string
        responses:
          200:
            description: OK
        tags:
        - sandbox
        security: []
      put:
        summary: UpdateSandbox
        description: UpdateSandbox (PUT)
        operationId: updatesandbox-put
        parameters:
        - in: path
          name: AccountSid
          type: string
        - in: path
          name: format
          type: string
        responses:
          200:
            description: OK
        tags:
        - sandbox
        security: []
  definitions: []