- swagger: "2.0"
  info:
    title: NewsWhip API
    description: Our API partners get complete access to our rankings in a machine-readable
      format (JSON, RSS), with the option of using country, city, topic and time filters
      for a deeper dive into the 200,000 new pieces of content we track every day.
    termsOfService: http://www.newswhip.com/PrivacyAndLegal
    version: v1
  host: api.newswhip.com
  basePath: v1/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    local/:
      get:
        summary: Local
        description: Pull list of localities.
        operationId: ""
        parameters:
        - in: query
          name: key
          description: API Key
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' local'
        security: []
    local/{city}/All/{time_period}:
      get:
        summary: Local
        description: Search local news.
        operationId: ""
        parameters:
        - in: path
          name: city
          description: Filters articles published in that city. See available cities
            below. i.e. London, New%20York,%20NY, Toronto
          type: string
          format: string
        - in: query
          name: key
          description: API Key
          type: string
          format: string
        - in: query
          name: sort_by
          description: 'One of the following: [default, fb_likes, fb_shares, fb_comments,
            fb_total, twitter, linkedin, fb_tw_and_li, nw_score, nw_max_score]. Defaults
            to default'
          type: string
          format: string
        - in: path
          name: time_period
          description: Filters articles published within the last X hours. X can be
            1, 3, 12, 24 or 168 hours)
          type: string
          format: string
        - in: query
          name: video_only
          description: true or false. Defaults to false.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' local'
        security: []
    publisher/:
      get:
        summary: Publisher
        description: Pull publishers.
        operationId: ""
        parameters:
        - in: query
          name: key
          description: API Key
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' publisher'
        security: []
    publisher/{publisher}/{time_period}:
      get:
        summary: Publisher
        description: Search news by publisiher.
        operationId: ""
        parameters:
        - in: query
          name: key
          description: API Key.
          type: string
          format: string
        - in: path
          name: publisher
          description: Returns all articles published within that domain or subdomain.
          type: string
          format: string
        - in: query
          name: sort_by
          description: 'One of the following: [default, fb_likes, fb_shares, fb_comments,
            fb_total, twitter, linkedin, fb_tw_and_li, nw_score, nw_max_score]. Defaults
            to default'
          type: string
          format: string
        - in: path
          name: time_period
          description: Filters articles published within the last X hours. X can be
            1, 3, 12, 24 or 168 hours)
          type: string
          format: string
        - in: query
          name: video_only
          description: true or false. Defaults to false.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' publisher'
        security: []
    region/:
      get:
        summary: Region
        description: Retrieve list of regions
        operationId: ""
        parameters:
        - in: query
          name: key
          description: API Key
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' region'
        security: []
    region/{region}/{category}/{time_period}:
      get:
        summary: Region
        description: Search news by region
        operationId: ""
        parameters:
        - in: path
          name: category
          description: Filters articles by {category}.
          type: string
          format: string
        - in: query
          name: key
          description: API key.
          type: string
          format: string
        - in: path
          name: region
          description: Filters articles published in that {region}
          type: string
          format: string
        - in: query
          name: sort_by
          description: 'One of the following: [default, fb_likes, fb_shares, fb_comments,
            fb_total, twitter, linkedin, fb_tw_and_li, nw_score, nw_max_score]. Defaults
            to default'
          type: string
          format: string
        - in: path
          name: time_period
          description: Filters articles published within the last X hours. X can be
            1, 3, 12, 24 or 168 hours)
          type: string
          format: string
        - in: query
          name: video_only
          description: true or false. Defaults to false.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' region'
        security: []
  definitions: []