- swagger: "2.0"
  info:
    title: Wordpress.org Categories API
    version: ~
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /categories:
      get:
        summary: List Categorys
        description: List Categorys
        operationId: list-categorys
        parameters:
        - in: query
          name: context
          description: 'Scope under which the request is made; determines fields present
            in response.n                    n                    n                    n                        n                            Default:
            viewn                        n                    n                    n                        One
            of: view, embed, edit'
          type: string
        - in: query
          name: exclude
          description: 'Ensure result set excludes specific ids.n                    n                    n                    n                        n                            Default:'
          type: string
        - in: query
          name: hide_empty
          description: Whether to hide resources not assigned to any posts.
          type: string
        - in: query
          name: include
          description: 'Limit result set to specific ids.n                    n                    n                    n                        n                            Default:'
          type: string
        - in: query
          name: order
          description: 'Order sort attribute ascending or descending.n                    n                    n                    n                        n                            Default:
            ascn                        n                    n                    n                        One
            of: asc, desc'
          type: string
        - in: query
          name: orderby
          description: 'Sort collection by resource attribute.n                    n                    n                    n                        n                            Default:
            namen                        n                    n                    n                        One
            of: id, include, name, slug, term_group, description, count'
          type: string
        - in: query
          name: page
          description: 'Current page of the collection.n                    n                    n                    n                        n                            Default:
            1'
          type: string
        - in: query
          name: parent
          description: Limit result set to resources assigned to a specific parent.
          type: string
        - in: query
          name: per_page
          description: 'Maximum number of items to be returned in result set.n                    n                    n                    n                        n                            Default:
            10'
          type: string
        - in: query
          name: post
          description: Limit result set to resources assigned to a specific post.
          type: string
        - in: query
          name: search
          description: Limit results to those matching a string.
          type: string
        - in: query
          name: slug
          description: Limit result set to resources with a specific slug.
          type: string
        responses:
          200:
            description: OK
        tags:
        - categories
        security: []
      post:
        summary: Create a Category
        description: Create a Category
        operationId: create-a-category
        parameters:
        - in: query
          name: description
          type: string
        - in: query
          name: name
          description: 'Required: true'
          type: string
        - in: query
          name: parent
          type: string
        - in: query
          name: slug
          type: string
        responses:
          200:
            description: OK
        tags:
        - categories
        security: []
    /categories/{id}:
      delete:
        summary: Delete a Category
        description: Delete a Category
        operationId: delete-a-category
        parameters:
        - in: query
          name: force
          description: Required to be true, as resource does not support trashing.
          type: string
        - in: path
          name: id
          type: string
        responses:
          200:
            description: OK
        tags:
        - categories
        security: []
      get:
        summary: Retrieve a Category
        description: Retrieve a Category
        operationId: retrieve-a-category
        parameters:
        - in: query
          name: context
          description: 'Scope under which the request is made; determines fields present
            in response.n                    n                    n                    n                        n                            Default:
            viewn                        n                    n                    n                        One
            of: view, embed, edit'
          type: string
        - in: path
          name: id
          type: string
        responses:
          200:
            description: OK
        tags:
        - categories
        security: []
      post:
        summary: Update a Category
        description: Update a Category
        operationId: update-a-category
        parameters:
        - in: query
          name: description
          type: string
        - in: path
          name: id
          type: string
        - in: query
          name: name
          type: string
        - in: query
          name: parent
          type: string
        - in: query
          name: slug
          type: string
        responses:
          200:
            description: OK
        tags:
        - categories
        security: []
  definitions: []