agger: "2.0"
info:
  title: Hearst Article Image Search
  description: A read-only service for the retrieval of Article Image content from
    the Hearst Magazines Content Management System. Contains a list of parameters
    and sample responses.
  termsOfService: http://developer.hearst.com/API_Terms_of_Use
  version: v1
host: api.hearstdigital.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []