- swagger: "2.0"
  info:
    title: CloudFlare Organization-level Firewall access rule API
    description: The API for managing CloudFlare Organization-level Firewall access
      rule
    termsOfService: https://www.cloudflare.com/terms/
    version: ~
  host: api.cloudflare.com
  basePath: /client/v4
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /organizations/:organization_id/firewall/access_rules/rules:
      get:
        summary: Search, sort, and filter IP/country access rules
        description: Search, sort, and filter IP/country access rules
        operationId: cloudflare-organizationlevel-firewall-access-rule-api
        parameters:
        - in: query
          name: configuration_target
          description: The rule configuration targetttttttttttttttip
          type: string
        - in: query
          name: configuration_value
          description: Search by IP, range, or country codetttttttttttttt1.2.3.4
          type: string
        - in: query
          name: direction
          description: Direction to order rulesttttttttttttttdesc
          type: string
        - in: query
          name: match
          description: Whether to match all search requirements or at least one (any)ttttttttttttttall
          type: string
        - in: query
          name: mode
          description: The action to apply to a matched requestttttttttttttttchallenge
          type: string
        - in: query
          name: order
          description: Field to order rules byttttttttttttttmode
          type: string
        - in: query
          name: page
          description: Page number of paginated resultstttttttttttttt1
          type: string
        - in: query
          name: per_page
          description: Number of rules per pagetttttttttttttt50
          type: string
        - in: header
          name: X-AUTH-EMAIL
          description: Email address associated with your account
          type: string
        - in: header
          name: X-AUTH-KEY
          description: API key generated on the My Account page
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      post:
        summary: Make a new IP, IP range, or country access rule for all zones owned
          by the organization
        description: Make a new IP, IP range, or country access rule for all zones owned
          by the organization
        operationId: cloudflare-organizationlevel-firewall-access-rule-api
        parameters:
        - in: query
          name: configuration
          description: Rule configurationtttttttttttttttttttttOne of the following:tttttttttttttttttttttttttttttShow
            definition &raquo;ttttttttttttttttttttttttttttttttttttttName /typetttttttttttDescription
            /exampletttttttttttConstraintstttttttttttttttttttttttttttttttttttttttttttttttttttttttttargettttttttttttttstring
          type: string
        - in: query
          name: mode
          description: The action to apply to a matched requestttttttttttttttchallenge
          type: string
        - in: query
          name: value
          description: The IP address to target in requeststtttttttttttttttttttttttttttttttttt1.2.3.4
          type: string
        - in: header
          name: X-AUTH-EMAIL
          description: Email address associated with your account
          type: string
        - in: header
          name: X-AUTH-KEY
          description: API key generated on the My Account page
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /organizations/:organization_id/firewall/access_rules/rules/:identifier:
      delete:
        summary: Remove an access rule so it is no longer evaluated during requests
        description: Remove an access rule so it is no longer evaluated during requests
        operationId: cloudflare-organizationlevel-firewall-access-rule-api
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      patch:
        summary: Update rule state and/or configuration
        description: Update rule state and/or configuration
        operationId: cloudflare-organizationlevel-firewall-access-rule-api
        parameters:
        - in: query
          name: configuration
          description: Rule configurationtttttttttttttttttttttOne of the following:tttttttttttttttttttttttttttttShow
            definition &raquo;ttttttttttttttttttttttttttttttttttttttName /typetttttttttttDescription
            /exampletttttttttttConstraintstttttttttttttttttttttttttttttttttttttttttttttttttttttttttargettttttttttttttstring
          type: string
        - in: query
          name: mode
          description: The action to apply to a matched requestttttttttttttttchallenge
          type: string
        - in: query
          name: value
          description: The IP address to target in requeststtttttttttttttttttttttttttttttttttt1.2.3.4
          type: string
        - in: header
          name: X-AUTH-EMAIL
          description: Email address associated with your account
          type: string
        - in: header
          name: X-AUTH-KEY
          description: API key generated on the My Account page
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []