- swagger: "2.0"
  info:
    title: CloudFlare Zone Subscription API
    description: The API for managing CloudFlare Zone Subscription
    termsOfService: https://www.cloudflare.com/terms/
    version: ~
  host: api.cloudflare.com
  basePath: /client/v4
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /user/billing/subscriptions/zones:
      get:
        summary: List all of your zone plan subscriptions
        description: List all of your zone plan subscriptions
        operationId: cloudflare-zone-subscription-api
        parameters:
        - in: query
          name: activated_on
          description: When the subscription was activated2014-03-01T12:20:00Z
          type: string
        - in: query
          name: cancelled_on
          description: When the subscription was cancelled2014-04-01T12:20:00Z
          type: string
        - in: query
          name: direction
          description: Direction to order subscriptionsdesc
          type: string
        - in: query
          name: expired_on
          description: When the subscription expired2014-04-02T12:20:00Z
          type: string
        - in: query
          name: expires_on
          description: When the subscription will expire2014-03-31T12:20:00Z
          type: string
        - in: query
          name: match
          description: Whether to match all search requirements or at least one (any)all
          type: string
        - in: query
          name: order
          description: Field to order subscriptions bystatus
          type: string
        - in: query
          name: page
          description: Page number of paginated results1
          type: string
        - in: query
          name: per_page
          description: Number of items per page20
          type: string
        - in: query
          name: price
          description: The price of the subscription that will be billed, in US dollars20
          type: string
        - in: query
          name: renewed_on
          description: When the subscription was renewed2014-05-11T12:20:00Z
          type: string
        - in: query
          name: status
          description: The state of the subscriptionactive
          type: string
        - in: header
          name: X-AUTH-EMAIL
          description: Email address associated with your account
          type: string
        - in: header
          name: X-AUTH-KEY
          description: API key generated on the My Account page
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /user/billing/subscriptions/zones/:identifier:
      get:
        summary: Billing subscription details
        description: Billing subscription details
        operationId: cloudflare-zone-subscription-api
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []