- swagger: "2.0"
  info:
    title: Hearst Source Search
    description: A read-only service for the retrieval of Source content from the Hearst
      Magazines Content Management System. Contains a list of parameters and sample
      responses.
    termsOfService: http://developer.hearst.com/API_Terms_of_Use
    version: v1
  host: api.hearstdigital.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    Source/search:
      get:
        summary: Source Search
        description: A read-only service for the retrieval of Source content from the
          Hearst Magazines Content Management System. Contains a list of parameters
          and sample responses.
        operationId: ""
        parameters:
        - in: query
          name: description
          type: string
          format: string
        - in: query
          name: id
          type: integer
          format: string
        - in: query
          name: limit
          type: integer
          format: string
        - in: query
          name: name
          type: string
          format: string
        - in: query
          name: organization_id
          type: integer
          format: string
        - in: query
          name: sort
          type: string
          format: string
        - in: query
          name: start
          type: integer
          format: string
        - in: query
          name: total
          type: integer
          format: string
        - in: query
          name: _callback
          type: string
          format: string
        - in: query
          name: _pretty
          type: integer
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' source'
        security: []
  definitions: []