- swagger: "2.0"
  info:
    title: Hearst Article Search
    description: ' read-only service for the retrieval of magazine and website content
      from the Hearst Magazines Content Management System. Contains a list of parameters
      and sample responses.'
    termsOfService: http://developer.hearst.com/API_Terms_of_Use
    version: v1
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    Article/search:
      get:
        summary: Article Search
        description: ' read-only service for the retrieval of magazine and website content
          from the Hearst Magazines Content Management System. Contains a list of parameters
          and sample responses.'
        operationId: ""
        parameters:
        - in: query
          name: ad_category_id
          type: string
          format: string
        - in: query
          name: article_category_id
          type: string
          format: string
        - in: query
          name: article_section_id
          type: string
          format: string
        - in: query
          name: article_type_id
          type: string
          format: string
        - in: query
          name: id
          type: string
          format: string
        - in: query
          name: keywords
          type: string
          format: string
        - in: query
          name: limit
          type: string
          format: string
        - in: query
          name: pages
          type: string
          format: string
        - in: query
          name: print_issue_date
          type: string
          format: string
        - in: query
          name: publish_date_begin
          type: string
          format: string
        - in: query
          name: shape
          type: string
          format: string
        - in: query
          name: site_id
          type: string
          format: string
        - in: query
          name: sort
          type: string
          format: string
        - in: query
          name: start
          type: string
          format: string
        - in: query
          name: title
          type: string
          format: string
        - in: query
          name: total
          type: string
          format: string
        - in: query
          name: url_name
          type: string
          format: string
        - in: query
          name: _callback
          type: string
          format: string
        - in: query
          name: _pretty
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - news
        - ' articles'
        security: []
  definitions: []