agger: "2.0"
info:
  title: Meetup Members API
  description: The API for managing Meetup members.
  termsOfService: http://www.meetup.com/terms/
  version: 1.0.0
host: api.meetup.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []