- swagger: "2.0"
  info:
    title: Fluxiom API
    description: The Fluxiom API allows you to hook into Fluxiom and connect it with
      other apps.
    termsOfService: http://www.fluxiom.com/terms
    version: v1
  host: '{subdomain}.fluxiom.com'
  basePath: /api/{format}
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /api/assets:
      get:
        summary: Get assets
        description: Get assets
        operationId: get-assets
        parameters:
        - in: query
          name: page
          description: page  tt integer tt current page number (defaults to 1)
          type: string
          format: string
        - in: query
          name: per_page
          description: per_page  tt integer tt number of items per page (max. 100)
          type: string
          format: string
        - in: query
          name: query
          description: query tt string tt search term
          type: string
          format: string
        - in: query
          name: tags
          description: tags  tt string tt tag names or IDs, comma separated
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      post:
        summary: Create asset
        description: Create asset
        operationId: create-asset
        parameters:
        - in: query
          name: description
          description: description   tt string
          type: string
          format: string
        - in: query
          name: file
          description: file          tt postdata  tt (required)
          type: string
          format: string
        - in: query
          name: tags
          description: tags          tt string    tt tag names or IDs, comma separated
          type: string
          format: string
        - in: query
          name: title
          description: title         tt string
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/assets/download/{id}:
      get:
        summary: Download asset
        description: Download asset
        operationId: download-asset
        parameters:
        - in: path
          name: ID
          description: The unique ID for the asset.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/assets/ID:
      get:
        summary: Get single asset
        description: Get single asset
        operationId: get-single-asset
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      put:
        summary: Update asset
        description: Update asset
        operationId: update-asset
        parameters:
        - in: query
          name: description
          description: description   tt string
          type: string
          format: string
        - in: query
          name: tags
          description: tags          tt string tt tag names or IDs, comma separated
          type: string
          format: string
        - in: query
          name: title
          description: title         tt string
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/assets/ID/versions:
      get:
        summary: Get asset versions
        description: Get asset versions
        operationId: get-asset-versions
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      post:
        summary: Create asset version
        description: Create asset version
        operationId: create-asset-version
        parameters:
        - in: query
          name: comment
          description: comment     tt string
          type: string
          format: string
        - in: query
          name: file
          description: file        tt postdata
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/assets/ID/versions/VID:
      get:
        summary: Get single asset version
        description: Get single asset version
        operationId: get-single-asset-version
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/assets/{id}:
      delete:
        summary: Delete asset
        description: Delete asset
        operationId: delete-asset
        parameters:
        - in: path
          name: id
          description: Unique id of the asset.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/tags:
      get:
        summary: Get tags
        description: Get tags
        operationId: get-tags
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      post:
        summary: Create tag
        description: Create tag
        operationId: create-tag
        parameters:
        - in: query
          name: tag
          description: tag tt string
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/tags/ID:
      get:
        summary: Get single tag
        description: Get single tag
        operationId: get-single-tag
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
      put:
        summary: Update tag
        description: Update tag
        operationId: update-tag
        parameters:
        - in: query
          name: tag
          description: tag tt string
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/tags/{id}:
      delete:
        summary: Delete tag
        description: Delete tag
        operationId: delete-tag
        parameters:
        - in: path
          name: id
          description: Unique id of the tag.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/user:
      get:
        summary: Get current user
        description: Get current user
        operationId: get-current-user
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/users:
      get:
        summary: Get users
        description: Get users
        operationId: get-users
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
    /api/users/{id}:
      get:
        summary: Get single user
        description: Get single user
        operationId: get-single-user
        parameters:
        - in: path
          name: id
          description: Unique id of the user.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []