- swagger: "2.0"
  info:
    title: Flickr Blogs API
    description: The API for managing Flickr Blogs
    termsOfService: https://www.flickr.com/services/api/tos/
    version: ~
  host: www.flickr.com
  basePath: /services/rest/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /?method=flickr.blogs.getList:
      get:
        summary: flickr.blogs.getList
        description: <div class=MethodDescription>Get a list of configured blogs for
          the calling user.</div>
        operationId: methodflickrblogsgetlist
        parameters:
        - in: query
          name: api_key
          description: Your API application key. See here for more details.
          type: string
        - in: query
          name: service
          description: Optionally only return blogs for a given service id.  You can
            get a list of from flickr.blogs.getServices().
          type: string
        responses:
          95:
            description: SSL is required - SSL is required to access the Flickr API.
          96:
            description: Invalid signature - The passed signature was invalid.
          97:
            description: Missing signature - The call required signing but no signature
              was sent.
          98:
            description: Login failed / Invalid auth token - The login details or auth
              token passed were invalid.
          99:
            description: User not logged in / Insufficient permissions - The method
              requires user authentication but the user was not logged in, or the authenticated
              method call did not have the required permissions.
          100:
            description: Invalid API Key - The API key passed was not valid or has expired.
          105:
            description: Service currently unavailable - The requested service is temporarily
              unavailable.
          106:
            description: Write operation failed - The requested operation failed due
              to a temporary issue.
          111:
            description: Format xxx not found - The requested response format was not
              found.
          112:
            description: Method xxx not found - The requested method was not found.
          114:
            description: Invalid SOAP envelope - The SOAP envelope send in the request
              could not be parsed.
          115:
            description: Invalid XML-RPC Method Call - The XML-RPC request document
              could not be parsed.
          116:
            description: Bad URL found - One or more arguments contained a URL that
              has been used for abuse on Flickr.
        tags:
        - ""
        security: []
    /?method=flickr.blogs.getServices:
      get:
        summary: flickr.blogs.getServices
        description: <div class=MethodDescription>Return a list of Flickr supported
          blogging services</div>
        operationId: methodflickrblogsgetservices
        parameters:
        - in: query
          name: api_key
          description: Your API application key. See here for more details.
          type: string
        responses:
          95:
            description: SSL is required - SSL is required to access the Flickr API.
          96:
            description: Invalid signature - The passed signature was invalid.
          97:
            description: Missing signature - The call required signing but no signature
              was sent.
          98:
            description: Login failed / Invalid auth token - The login details or auth
              token passed were invalid.
          99:
            description: User not logged in / Insufficient permissions - The method
              requires user authentication but the user was not logged in, or the authenticated
              method call did not have the required permissions.
          100:
            description: Invalid API Key - The API key passed was not valid or has expired.
          105:
            description: Service currently unavailable - The requested service is temporarily
              unavailable.
          106:
            description: Write operation failed - The requested operation failed due
              to a temporary issue.
          111:
            description: Format xxx not found - The requested response format was not
              found.
          112:
            description: Method xxx not found - The requested method was not found.
          114:
            description: Invalid SOAP envelope - The SOAP envelope send in the request
              could not be parsed.
          115:
            description: Invalid XML-RPC Method Call - The XML-RPC request document
              could not be parsed.
          116:
            description: Bad URL found - One or more arguments contained a URL that
              has been used for abuse on Flickr.
        tags:
        - ""
        security: []
    /?method=flickr.blogs.postPhoto:
      get:
        summary: flickr.blogs.postPhoto
        description: <div class=MethodDescription></div>
        operationId: methodflickrblogspostphoto
        parameters:
        - in: query
          name: api_key
          description: Your API application key. See here for more details.
          type: string
        - in: query
          name: blog_id
          description: The id of the blog to post to.
          type: string
        - in: query
          name: blog_password
          description: The password for the blog (used when the blog does not have a
            stored password).
          type: string
        - in: query
          name: description
          description: The blog post body
          type: string
        - in: query
          name: photo_id
          description: The id of the photo to blog
          type: string
        - in: query
          name: service
          description: A Flickr supported blogging service.  Instead of passing a blog
            id you can pass a service id and well post to the first blog of that service
            we find.
          type: string
        - in: query
          name: title
          description: The blog post title
          type: string
        responses:
          95:
            description: SSL is required - SSL is required to access the Flickr API.
          96:
            description: Invalid signature - The passed signature was invalid.
          97:
            description: Missing signature - The call required signing but no signature
              was sent.
          98:
            description: Login failed / Invalid auth token - The login details or auth
              token passed were invalid.
          99:
            description: User not logged in / Insufficient permissions - The method
              requires user authentication but the user was not logged in, or the authenticated
              method call did not have the required permissions.
          100:
            description: Invalid API Key - The API key passed was not valid or has expired.
          105:
            description: Service currently unavailable - The requested service is temporarily
              unavailable.
          106:
            description: Write operation failed - The requested operation failed due
              to a temporary issue.
          111:
            description: Format xxx not found - The requested response format was not
              found.
          112:
            description: Method xxx not found - The requested method was not found.
          114:
            description: Invalid SOAP envelope - The SOAP envelope send in the request
              could not be parsed.
          115:
            description: Invalid XML-RPC Method Call - The XML-RPC request document
              could not be parsed.
          116:
            description: Bad URL found - One or more arguments contained a URL that
              has been used for abuse on Flickr.
          1:
            description: Blog not found - The blog id was not the id of a blog belonging
              to the calling user
          2:
            description: Photo not found - The photo id was not the id of a public photo
          3:
            description: Password needed - A password is not stored for the blog and
              one was not passed with the request
          4:
            description: Blog post failed - The blog posting failed (a blogging API
              failure of some sort)
        tags:
        - ""
        security: []
  definitions: []