- swagger: "2.0"
  info:
    title: Flickr Panda API
    description: The API for managing Flickr Panda
    termsOfService: https://www.flickr.com/services/api/tos/
    version: ~
  host: www.flickr.com
  basePath: /services/rest/
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /?method=flickr.panda.getList:
      get:
        summary: flickr.panda.getList
        description: <div class=MethodDescription>Return a list of <a href=http://www.flickr.com/explore/panda>Flickr
          pandas</a>, from whom you can request photos using the <a href=/services/api/flickr.panda.getPhotos.htm>flickr.panda.getPhotos</a>
          API method.rn<br/><br/>rnMore information about the pandas can be found on
          the <a href=http://code.flickr.com/blog/2009/03/03/panda-tuesday-the-history-of-the-panda-new-apis-explore-and-you/>dev
          blog</a>.</div>
        operationId: methodflickrpandagetlist
        parameters:
        - in: query
          name: api_key
          description: Your API application key. See here for more details.
          type: string
        responses:
          100:
            description: Invalid API Key - The API key passed was not valid or has expired.
          105:
            description: Service currently unavailable - The requested service is temporarily
              unavailable.
          106:
            description: Write operation failed - The requested operation failed due
              to a temporary issue.
          111:
            description: Format xxx not found - The requested response format was not
              found.
          112:
            description: Method xxx not found - The requested method was not found.
          114:
            description: Invalid SOAP envelope - The SOAP envelope send in the request
              could not be parsed.
          115:
            description: Invalid XML-RPC Method Call - The XML-RPC request document
              could not be parsed.
          116:
            description: Bad URL found - One or more arguments contained a URL that
              has been used for abuse on Flickr.
        tags:
        - ""
        security: []
    /?method=flickr.panda.getPhotos:
      get:
        summary: flickr.panda.getPhotos
        description: <div class=MethodDescription>Ask the <a href=http://www.flickr.com/explore/panda>Flickr
          Pandas</a> for a list of recent public (and safe) photos.rn<br/><br/>rnMore
          information about the pandas can be found on the <a href=http://code.flickr.com/blog/2009/03/03/panda-tuesday-the-history-of-the-panda-new-apis-explore-and-you/>dev
          blog</a>.</div>
        operationId: methodflickrpandagetphotos
        parameters:
        - in: query
          name: api_key
          description: Your API application key. See here for more details.
          type: string
        - in: query
          name: extras
          description: 'A comma-delimited list of extra information to fetch for each
            returned record. Currently supported fields are: description, license, date_upload,
            date_taken, owner_name, icon_server, original_format, last_update, geo,
            tags, machine_tags, o_dims, views, media, path_alias, url_sq, url_t, url_s,
            url_q, url_m, url_n, url_z, url_c, url_l, url_o'
          type: string
        - in: query
          name: page
          description: The page of results to return. If this argument is omitted, it
            defaults to 1.
          type: string
        - in: query
          name: panda_name
          description: The name of the panda to ask for photos from. There are currently
            three pandas named:ling linghsing hsingwang wangYou can fetch a list of
            all the current pandas using the flickr.panda.getList API method.
          type: string
        - in: query
          name: per_page
          description: Number of photos to return per page. If this argument is omitted,
            it defaults to 100. The maximum allowed value is 500.
          type: string
        responses:
          100:
            description: Invalid API Key - The API key passed was not valid or has expired.
          105:
            description: Service currently unavailable - The requested service is temporarily
              unavailable.
          106:
            description: Write operation failed - The requested operation failed due
              to a temporary issue.
          111:
            description: Format xxx not found - The requested response format was not
              found.
          112:
            description: Method xxx not found - The requested method was not found.
          114:
            description: Invalid SOAP envelope - The SOAP envelope send in the request
              could not be parsed.
          115:
            description: Invalid XML-RPC Method Call - The XML-RPC request document
              could not be parsed.
          116:
            description: Bad URL found - One or more arguments contained a URL that
              has been used for abuse on Flickr.
          1:
            description: Required parameter missing. - One or more required parameters
              was not included with your request.
          2:
            description: Unknown panda - You requested a panda we havent met yet.
        tags:
        - ""
        security: []
  definitions: []