- swagger: "2.0"
  info:
    title: Reddit Miscellaneous API
    description: API for manageming Reddit miscellaneous.
    termsOfService: https://github.com/reddit/reddit/wiki/API
    version: ~
  host: www.reddit.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /api/v1/scopes:
      get:
        summary: Retrieve descriptions of reddit&#39;s OAuth2 scopes.
        description: Retrieve descriptions of reddit&#39;s OAuth2 scopes.
        operationId: misc
        parameters:
        - in: query
          name: scopes
          description: (optional) An OAuth2 scope string
          type: string
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []