- swagger: "2.0"
  info:
    title: URL Shortener API
    description: Lets you create, inspect, and manage goo.gl short URLs
    contact:
      name: Google
      url: https://google.com
    version: v1
  host: www.googleapis.com
  basePath: /urlshortener/v1
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /url:
      get:
        summary: Get URL
        description: Expands a short URL or gets creation time and analytics.
        operationId: urlshortener.url.get
        parameters:
        - in: query
          name: projection
          description: Additional information to return.
          type: string
          format: string
        - in: query
          name: shortUrl
          description: The short URL, including the protocol.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - url
        security: []
      parameters:
        summary: Get URL Parameters
        description: ""
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - url
        security: []
      post:
        summary: Add URL
        description: Creates a new short URL.
        operationId: urlshortener.url.insert
        responses:
          200:
            description: OK
        tags:
        - url
        security: []
    /url/history:
      get:
        summary: Get URL History
        description: Retrieves a list of URLs shortened by a user.
        operationId: urlshortener.url.list
        parameters:
        - in: query
          name: projection
          description: Additional information to return.
          type: string
          format: string
        - in: query
          name: start-token
          description: Token for requesting successive pages of results.
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - url
        security: []
      parameters:
        summary: Get URL History Parameters
        description: ""
        operationId: ""
        responses:
          200:
            description: OK
        tags:
        - url
        security: []
  definitions:
    AnalyticsSnapshot:
      properties:
        browsers:
          description: This is a default description.
          type: parameters
        countries:
          description: This is a default description.
          type: parameters
        longUrlClicks:
          description: This is a default description.
          type: parameters
        platforms:
          description: This is a default description.
          type: parameters
        referrers:
          description: This is a default description.
          type: parameters
        shortUrlClicks:
          description: This is a default description.
          type: parameters
    AnalyticsSummary:
      properties: []
    StringCount:
      properties:
        count:
          description: This is a default description.
          type: parameters
        id:
          description: This is a default description.
          type: parameters
    Url:
      properties:
        created:
          description: This is a default description.
          type: parameters
        id:
          description: This is a default description.
          type: parameters
        kind:
          description: This is a default description.
          type: parameters
        longUrl:
          description: This is a default description.
          type: parameters
        status:
          description: This is a default description.
          type: parameters
    UrlHistory:
      properties:
        items:
          description: This is a default description.
          type: parameters
        itemsPerPage:
          description: This is a default description.
          type: parameters
        kind:
          description: This is a default description.
          type: parameters
        nextPageToken:
          description: This is a default description.
          type: parameters
        totalItems:
          description: This is a default description.
          type: parameters