- swagger: "2.0"
  info:
    title: Github Events API
    version: ""
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /events:
      get:
        summary: DeletePullRequestComment
        description: DeletePullRequestComment
        operationId: deletepullrequestcomment
        parameters:
        - in: query
          name: User-Agent
        responses:
          200:
            description: OK
        tags:
        - ""
        security: []
  definitions: []