- swagger: "2.0"
  info:
    title: APIMetrics Reports API
    description: The API for managing APIMetrics reports.
    termsOfService: http://apimetrics.io/tos/
    contact:
      name: APIMetrics
      url: http://apimetrics.io/contact/
      email: info@apimetrics.com
    version: "2"
  host: client.apimetrics.io
  basePath: /api/2
  schemes:
  - http
  produces:
  - application/json
  consumes:
  - application/json
  paths:
    /reports/:
      get:
        summary: List all Reports
        description: List all Reports
        operationId: listAllReports
        responses:
          200:
            description: OK
        tags:
        - Reports
        security: []
      post:
        summary: Create a new Report
        description: Create a new Report
        operationId: createANewReport
        parameters:
        - in: body
          name: body
          description: '{     meta: {         name: Minimal Report name     } }'
          schema:
            $ref: '#/definitions/holder'
        responses:
          200:
            description: OK
        tags:
        - Reports
        security: []
    /reports/{id}/:
      delete:
        summary: Delete a Report
        description: Delete a Report
        operationId: deleteAReport
        parameters:
        - in: path
          name: id
          description: ID string of Report you are updating
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - Reports
        security: []
      get:
        summary: Get an existing Report
        description: Get an existing Report
        operationId: getAnExistingReport
        parameters:
        - in: path
          name: id
          description: ID string of Report you are updating
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - Reports
        security: []
      put:
        summary: Update an existing Report
        description: Update an existing Report
        operationId: updateAnExistingReport
        parameters:
        - in: body
          name: body
          description: '{     meta: {         name: Minimal Report name bad create     },     groups:
            [         {             name: Group Name,             rows: [                 {                     call_id:
            __PARENT_ID__,                     location_id:                  },                 {                     call_id:
            __PARENT_ID__,                     location_id:                  }             ]         },         {             name:
            Group Name 2,             rows: [         '
          schema:
            $ref: '#/definitions/holder'
        - in: path
          name: id
          description: ID string of Report you are updating
          type: string
          format: string
        responses:
          200:
            description: OK
        tags:
        - Reports
        security: []
  definitions: []